
-- Add metadata jsonb column to frameworks table
ALTER TABLE public.frameworks ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT NULL;

-- Seed metadata for all 10 existing frameworks
UPDATE public.frameworks SET metadata = '{"primaryGoal":"Converter leads em clientes através de copy persuasivo","recommendedFunnelStage":"bofu","bestFor":["Landing pages","Emails de vendas","Posts de lançamento"],"avoidWhen":["Conteúdo educativo puro","Primeiros contatos com a audiência"],"toneGuidelines":"Direto, persuasivo e orientado a ação","lengthGuidelines":"Curto a médio — 150 a 300 palavras","ctaGuidelines":"CTA forte e único, com senso de urgência"}'::jsonb WHERE name = 'AIDA';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Converter identificando dores e oferecendo solução clara","recommendedFunnelStage":"bofu","bestFor":["Posts de vendas","Anúncios","Emails de follow-up"],"avoidWhen":["Conteúdo inspiracional","Construção de comunidade"],"toneGuidelines":"Empático na dor, confiante na solução","lengthGuidelines":"Curto — 100 a 250 palavras","ctaGuidelines":"CTA direto ligado à solução apresentada"}'::jsonb WHERE name = 'PAS';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Construir conexão emocional e inspirar através de narrativa","recommendedFunnelStage":"tofu","bestFor":["Posts de marca pessoal","Conteúdo viral","Construção de audiência"],"avoidWhen":["Conteúdo técnico ou tutorial","Comunicação corporativa formal"],"toneGuidelines":"Emocional, autêntico e envolvente","lengthGuidelines":"Médio a longo — 200 a 500 palavras","ctaGuidelines":"CTA suave, convidando à reflexão ou compartilhamento"}'::jsonb WHERE name = 'Storytelling Herói';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Educar a audiência com conteúdo claro e escaneável","recommendedFunnelStage":"mofu","bestFor":["Carrosséis","Threads","Newsletters"],"avoidWhen":["Storytelling emocional","Conteúdo de opinião"],"toneGuidelines":"Claro, objetivo e didático","lengthGuidelines":"Variável — depende do número de itens","ctaGuidelines":"CTA para salvar, compartilhar ou aprofundar o tema"}'::jsonb WHERE name = 'Lista Numerada';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Demonstrar autoridade mostrando transformação real","recommendedFunnelStage":"mofu","bestFor":["Provas sociais","Cases de sucesso","Posts motivacionais"],"avoidWhen":["Primeiro contato com a audiência","Conteúdo sem dados reais"],"toneGuidelines":"Confiante e baseado em resultados","lengthGuidelines":"Curto a médio — 150 a 300 palavras","ctaGuidelines":"CTA convidando a iniciar a mesma jornada"}'::jsonb WHERE name = 'Antes/Depois';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Humanizar a marca e criar proximidade com a audiência","recommendedFunnelStage":"tofu","bestFor":["Stories","Reels","Posts pessoais"],"avoidWhen":["Conteúdo de vendas diretas","Comunicação formal"],"toneGuidelines":"Informal, vulnerável e honesto","lengthGuidelines":"Curto a médio — 100 a 250 palavras","ctaGuidelines":"CTA para comentários ou identificação pessoal"}'::jsonb WHERE name = 'Bastidores';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Gerar debate, engajamento e visibilidade com posicionamento forte","recommendedFunnelStage":"tofu","bestFor":["Posts de opinião","LinkedIn polêmico","Twitter/X threads"],"avoidWhen":["Primeiras impressões com clientes","Conteúdo institucional"],"toneGuidelines":"Provocativo mas respeitoso, com argumentação sólida","lengthGuidelines":"Curto a médio — 150 a 300 palavras","ctaGuidelines":"CTA para debate: perguntas abertas ao final"}'::jsonb WHERE name = 'Opinião Controversa';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Ensinar processos práticos de forma detalhada e acionável","recommendedFunnelStage":"mofu","bestFor":["Artigos","Carrosséis educativos","Vídeos tutorial"],"avoidWhen":["Conteúdo de awareness","Posts curtos de engajamento"],"toneGuidelines":"Didático, paciente e detalhado","lengthGuidelines":"Médio a longo — 300 a 800 palavras","ctaGuidelines":"CTA para praticar, salvar ou compartilhar com alguém"}'::jsonb WHERE name = 'Tutorial Passo-a-Passo';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Conectar experiência pessoal a lição prática com CTA claro","recommendedFunnelStage":"mofu","bestFor":["Posts de marca pessoal","LinkedIn narrativo","Newsletter"],"avoidWhen":["Conteúdo puramente técnico","Listas e tutoriais"],"toneGuidelines":"Pessoal, reflexivo e inspirador","lengthGuidelines":"Médio — 200 a 400 palavras","ctaGuidelines":"CTA acionável e direto ligado à lição"}'::jsonb WHERE name = 'Story-Lesson-CTA';

UPDATE public.frameworks SET metadata = '{"primaryGoal":"Demonstrar domínio técnico desconstruindo conceitos complexos","recommendedFunnelStage":"mofu","bestFor":["Posts de autoridade","Artigos técnicos","LinkedIn thought leadership"],"avoidWhen":["Conteúdo para iniciantes","Posts de engajamento leve"],"toneGuidelines":"Analítico, confiante e acessível","lengthGuidelines":"Médio a longo — 250 a 500 palavras","ctaGuidelines":"CTA para aprofundamento ou aplicação prática"}'::jsonb WHERE name = 'Authority Breakdown';
